### PR TITLE
Add Maximize windows when they are created.

### PR DESCRIPTION
**Pull request by egrieco**
This was the only feature missing from your excellent extension. :)

I haven't written many web extensions so please let me know if I missed anything.

### CODE REVIEW

**Comment by ericchase** [comment]
Your windows don't open maximized by default?

**Comment by ericchase** [comment]
Hmm, I guess the browser uses the last state for new windows.

**Comment by ericchase** [comment]
Since you took the time and effort to write out the additions, I guess I have to look it over.

**Comment by ericchase** [comment]
I have to warn you that I haven't done this before, and I made the mistake of not updating the repo for when I released the last update. I'll try fixing the merge issues in here if I can.

**Comment by ericchase** [comment]
Jeez, github makes this very confusing.

**Comment by ericchase** [comment]
Ah ok, this wasn't the one I released an update for. I was just making some minor changes. Most of these files should be good to go then.

**Comment by ericchase** [comment]
Crap, it looks like I messed something up.

**Comment by ericchase** [comment]
Alright, I think I have learned a bit how Github works. It seems they just gave me the power to screw up your repository through this pull request. Which I proceeded to do, since I wasn't sure what was going on. Luckily, the changes you made are saved here in this pull request. Sorry for messing this up Cx

**Comment by ericchase** [comment]
Alright, I fixed the master repo and was able to keep your name on your changes.

**Comment by ericchase** [comment]
I published the changes. As for the repository, I had to rewrite it's history to cleanup the mess I made, so rebase yours back onto mine when you get the chance.

**Comment by egrieco** [comment]
Wow, you are quick merging pull requests! :)

The extension updated automatically in my browser and is working perfectly. Thank you so much for writing this extension. The window size issue has been bugging me for years.

As for the state of the git repo, no worries. I know a lot of Git-fu. ;)

**Pull request merged**
